package com.hibernate.entities;
// Generated 7-Jan-2019 9:27:02 PM by Hibernate Tools 4.3.1



/**
 * Action generated by hbm2java
 */
public class Action  implements java.io.Serializable {


     private int idAction;
     private String libAction;
     private String descpAction;

    public Action() {
    }

	
    public Action(int idAction) {
        this.idAction = idAction;
    }
    public Action(int idAction, String libAction, String descpAction) {
       this.idAction = idAction;
       this.libAction = libAction;
       this.descpAction = descpAction;
    }
   
    public int getIdAction() {
        return this.idAction;
    }
    
    public void setIdAction(int idAction) {
        this.idAction = idAction;
    }
    public String getLibAction() {
        return this.libAction;
    }
    
    public void setLibAction(String libAction) {
        this.libAction = libAction;
    }
    public String getDescpAction() {
        return this.descpAction;
    }
    
    public void setDescpAction(String descpAction) {
        this.descpAction = descpAction;
    }




}


