package com.hibernate.entities;
// Generated 7-Jan-2019 9:27:02 PM by Hibernate Tools 4.3.1



/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String idCountry;
     private String idGovernorate;
     private Integer idStateCountry;
     private String libCountryAr;
     private String libCountryEn;
     private String libDescpCountry;

    public Country() {
    }

	
    public Country(String idCountry) {
        this.idCountry = idCountry;
    }
    public Country(String idCountry, String idGovernorate, Integer idStateCountry, String libCountryAr, String libCountryEn, String libDescpCountry) {
       this.idCountry = idCountry;
       this.idGovernorate = idGovernorate;
       this.idStateCountry = idStateCountry;
       this.libCountryAr = libCountryAr;
       this.libCountryEn = libCountryEn;
       this.libDescpCountry = libDescpCountry;
    }
   
    public String getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(String idCountry) {
        this.idCountry = idCountry;
    }
    public String getIdGovernorate() {
        return this.idGovernorate;
    }
    
    public void setIdGovernorate(String idGovernorate) {
        this.idGovernorate = idGovernorate;
    }
    public Integer getIdStateCountry() {
        return this.idStateCountry;
    }
    
    public void setIdStateCountry(Integer idStateCountry) {
        this.idStateCountry = idStateCountry;
    }
    public String getLibCountryAr() {
        return this.libCountryAr;
    }
    
    public void setLibCountryAr(String libCountryAr) {
        this.libCountryAr = libCountryAr;
    }
    public String getLibCountryEn() {
        return this.libCountryEn;
    }
    
    public void setLibCountryEn(String libCountryEn) {
        this.libCountryEn = libCountryEn;
    }
    public String getLibDescpCountry() {
        return this.libDescpCountry;
    }
    
    public void setLibDescpCountry(String libDescpCountry) {
        this.libDescpCountry = libDescpCountry;
    }




}


