package com.hibernate.entities;
// Generated 7-Jan-2019 9:27:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private Integer id;
     private String title;
     private int price;
     private Set coursesStudentses = new HashSet(0);

    public Courses() {
    }

	
    public Courses(String title, int price) {
        this.title = title;
        this.price = price;
    }
    public Courses(String title, int price, Set coursesStudentses) {
       this.title = title;
       this.price = price;
       this.coursesStudentses = coursesStudentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Set getCoursesStudentses() {
        return this.coursesStudentses;
    }
    
    public void setCoursesStudentses(Set coursesStudentses) {
        this.coursesStudentses = coursesStudentses;
    }




}


